### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-serving-content-with-express-OctGcX#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://kisyular-kfxl35erbteu5octgcx.herokuapp.com/) and meets the following criteria:

- [x] No code is repeated in your files; create a partial for any shared elements (`nav`, `head`, `header`, etc.)
- [x] Make a navigation to move throughout your site, using `forEach` to create a set of links to other data pages
- [x] Each item should have an object with an image, a link, a title, and more properties based on your topic (i.e. sandwich ingredients, movie release date, etc.)
- [x] Include at least 3 data pages and a homepage; routes should be created in Express for each
- [x] Use data appropriately with HTML tags (paragraphs in `p` tags, headings in `h1`-`h6`, etc.)
- [x] Use `express.static` to create a folder for static assets (images, stylesheets, etc.)
- [x] Include a `.gitignore` file so that `node_modules` and any other unnecessary files are not commited to github

However, I am having an issue with deploying to heroku. Everytime I get an error **_Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details._** when I try to follow my [App Link](https://kisyular-kfxl35erbteu5octgcx.herokuapp.com/).

I have tried to debug my code and search for online help but I can seem to pinpoint what is wrong. Many online solutions says that I should install "Express" which I have already did, but the error os still there.

**Comment by stuartpearman** [comment]
If you run `heroku logs` in your terminal, it should print out an error log. That should give you some more useful errors to work with. If you get stumped reach out to me on Slack and we can work through it 🙂

**Comment by kisyular** [comment]
@stuartpearman 
Kindly take a look

**Comment by stuartpearman** [comment]
Hi Rellika,

Everything seems to work ok, but there are some issues with your code. It may take some time to go through everything, are you busy tomorrow or would you be free to stop by office hours at some point?

**Comment by kisyular** [comment]
I added the changes you suggested. Kindly take a look and let me know

**Comment by stuartpearman** [comment]
Looks great Rellika! Nice work :+1:

**Comment by stuartpearman** [comment]
:shipit:
